'use client';

import React, { useState, useEffect } from 'react';
import { useWorkspace } from '@/lib/store';
import { AiInboxItem, Deal, Email, Task } from '@/types';
type Stage = Deal['stage'];
import { 
  Inbox, Sparkles, CheckSquare, Mail, Calendar, 
  ArrowRight, ShieldCheck, RefreshCw, Send, 
  Clock, ArrowUpRight, BarChart2, CheckCircle2 
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { motion, AnimatePresence } from 'motion/react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';

export default function AiInboxPage() {
  const { 
    aiInbox, 
    completeAiInboxItem, 
    addEmail, 
    updateDealStage,
    addTask,
    user,
    deals
  } = useWorkspace();

  const [activeTab, setActiveTab] = useState<'pending' | 'completed'>('pending');
  const [selectedItemId, setSelectedItemId] = useState<string | null>(null);

  // Editable email body
  const [editedBody, setEditedBody] = useState('');

  

  // Filter items by tab
  const items = aiInbox.filter(item => {
    if (activeTab === 'pending') return item.status === 'pending';
    return item.status === 'completed';
  });

  // Automatically select the first item when items change or tab changes
  useEffect(() => {
    if (items.length > 0) {
      const exists = items.some(x => x.id === selectedItemId);
      if (!exists) {
        setSelectedItemId(items[0].id);
        if (items[0].type === 'email' && items[0].actionData?.body) {
          setEditedBody(items[0].actionData.body);
        }
      }
    } else {
      setSelectedItemId(null);
    }
  }, [items, selectedItemId, activeTab]);

  const selectedItem = aiInbox.find(x => x.id === selectedItemId);

  const targetDeal = selectedItem?.type === 'crm' && selectedItem.actionData?.dealId
    ? deals.find(d => d.id === selectedItem.actionData.dealId)
    : null;

  const handleSelectItem = (item: AiInboxItem) => {
    setSelectedItemId(item.id);
    if (item.type === 'email' && item.actionData?.body) {
      setEditedBody(item.actionData.body);
    }
  };

  const handleApproveAction = async (item: AiInboxItem) => {
    if (item.status === 'completed') return;

    try {
      if (item.type === 'email') {
        const { to, toName, subject } = item.actionData;
        addEmail({
          to,
          toName,
          subject,
          body: editedBody || item.actionData.body,
          status: 'sent',
          aiGenerated: true
        });
        toast.success(`Approved and sent draft to ${toName}`);
      } 
      else if (item.type === 'crm') {
        const { dealId, targetStage } = item.actionData;
        await updateDealStage(dealId, targetStage as Stage);
        toast.success(`CRM Stage updated successfully`);
      } 
      else if (item.type === 'meeting') {
        const { extractedTasks } = item.actionData;
        if (extractedTasks && user) {
          extractedTasks.forEach((tTitle: string) => {
            addTask({
              title: tTitle,
              description: 'AI Extracted from meeting summary notes',
              status: 'todo',
              priority: 'high',
              dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 2 days from now
              tags: ['ai-extracted'],
              subtasks: [],
              assignee: user
            });
          });
          toast.success(`Generated ${extractedTasks.length} tasks in task list`);
        }
      }

      completeAiInboxItem(item.id);
      setSelectedItemId(null);
    } catch (e) {
      toast.error('Failed to complete AI action');
    }
  };

  const getIcon = (type: string) => {
    switch (type) {
      case 'email': return <Mail className="w-4 h-4 text-blue-500" />;
      case 'crm': return <BarChart2 className="w-4 h-4 text-emerald-500" />;
      case 'meeting': return <Calendar className="w-4 h-4 text-purple-500" />;
      default: return <CheckSquare className="w-4 h-4 text-indigo-500" />;
    }
  };

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto w-full flex flex-col gap-6 h-screen overflow-hidden text-foreground bg-background select-none">
      
      {/* Header */}
      <div className="shrink-0 flex items-center justify-between pb-4 border-b border-border">
        <div>
          <h1 className="text-xl font-bold flex items-center gap-2">
            <Inbox className="w-5 h-5 text-indigo-500" />
            AI Action Inbox
          </h1>
          <p className="text-xs text-muted-foreground mt-1">
            Review, edit, and approve proactive suggestions generated by your AI Chief of Staff.
          </p>
        </div>

        <div className="flex p-0.5 bg-black/[0.04] dark:bg-white/[0.04] rounded-lg border border-border">
          <button
            onClick={() => {
              setActiveTab('pending');
              setSelectedItemId(null);
            }}
            className={cn(
              "px-3 py-1 text-xs font-semibold rounded-md transition-all cursor-pointer",
              activeTab === 'pending' ? "bg-card text-foreground shadow-xs" : "text-muted-foreground hover:text-foreground"
            )}
          >
            Pending Actions ({aiInbox.filter(x => x.status === 'pending').length})
          </button>
          <button
            onClick={() => {
              setActiveTab('completed');
              setSelectedItemId(null);
            }}
            className={cn(
              "px-3 py-1 text-xs font-semibold rounded-md transition-all cursor-pointer",
              activeTab === 'completed' ? "bg-card text-foreground shadow-xs" : "text-muted-foreground hover:text-foreground"
            )}
          >
            Completed
          </button>
        </div>
      </div>

      {/* Main Grid */}
      <div className="flex-1 min-h-0 grid grid-cols-1 lg:grid-cols-5 gap-6">
        
        {/* Left Column - List of Items */}
        <div className="lg:col-span-2 border border-border rounded-xl flex flex-col bg-card overflow-hidden">
          <div className="p-4 border-b border-border/60 bg-muted/10 shrink-0">
            <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">
              Action Notifications
            </span>
          </div>

          <div className="flex-1 overflow-y-auto divide-y divide-border/40 p-2 space-y-1.5 [scrollbar-width:none] [-ms-overflow-style:none] [&::-webkit-scrollbar]:hidden">
            <AnimatePresence mode="popLayout">
              {items.map(item => {
                const isSelected = item.id === selectedItemId;
                return (
                  <motion.div
                    key={item.id}
                    layoutId={item.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, x: -10 }}
                    onClick={() => handleSelectItem(item)}
                    className={cn(
                      "p-3 rounded-lg border text-left cursor-pointer transition-all flex items-start gap-3 relative group select-none",
                      isSelected 
                        ? "bg-indigo-500/[0.03] border-indigo-500/30 shadow-xs" 
                        : "bg-card border-border/80 hover:border-indigo-500/20"
                    )}
                  >
                    <div className="mt-0.5 shrink-0">
                      {item.status === 'pending' ? (
                        <button 
                          onClick={(e) => {
                            e.stopPropagation();
                            handleApproveAction(item);
                          }}
                          className="w-4 h-4 rounded-full border border-border flex items-center justify-center hover:bg-emerald-500/10 hover:border-emerald-500 transition-colors bg-background"
                          title="Quick Approve"
                        >
                          <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 opacity-0 group-hover:opacity-100 transition-opacity" />
                        </button>
                      ) : (
                        <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                      )}
                    </div>

                    <div className="min-w-0 flex-1 flex flex-col gap-1 pr-1">
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-xs font-bold truncate text-foreground">{item.title}</span>
                        <Badge variant="outline" className="text-[8px] tracking-wider uppercase font-bold py-0 px-1.5 shrink-0 bg-background">
                          {item.type}
                        </Badge>
                      </div>
                      <p className="text-[10px] text-muted-foreground line-clamp-2 leading-relaxed">{item.description}</p>
                      <span className="text-[9px] text-muted-foreground/60 font-mono mt-1">{format(new Date(item.createdAt), 'MMM d, h:mm a')}</span>
                    </div>
                  </motion.div>
                );
              })}
            </AnimatePresence>

            {items.length === 0 && (
              <div className="h-full flex flex-col items-center justify-center text-center p-8 text-muted-foreground my-12">
                <ShieldCheck className="w-10 h-10 opacity-20 mb-3 text-indigo-500" />
                <h4 className="text-xs font-bold text-foreground">Inbox Empty</h4>
                <p className="text-[10px] mt-1">No AI action alerts outstanding. Good job!</p>
              </div>
            )}
          </div>
        </div>

        {/* Right Column - Review Details */}
        <div className="lg:col-span-3 border border-border rounded-xl flex flex-col bg-card overflow-hidden">
          <AnimatePresence mode="wait">
            {selectedItem ? (
              <motion.div 
                key={selectedItem.id}
                initial={{ opacity: 0, x: 10 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -10 }}
                transition={{ duration: 0.15 }}
                className="flex-1 flex flex-col h-full overflow-hidden"
              >
                {/* Panel Header */}
                <div className="p-4 border-b border-border bg-muted/10 shrink-0 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    {getIcon(selectedItem.type)}
                    <span className="text-[11px] font-bold text-muted-foreground uppercase tracking-widest">
                      Review Action Details
                    </span>
                  </div>
                  <Badge className="bg-indigo-500/10 text-indigo-500 border-indigo-500/20 text-[9px] uppercase font-bold">
                    {selectedItem.status}
                  </Badge>
                </div>

                {/* Panel Scrollable Content */}
                <div className="flex-1 overflow-y-auto p-5 space-y-4 [scrollbar-width:none] [-ms-overflow-style:none] [&::-webkit-scrollbar]:hidden">
                  <div className="space-y-1">
                    <h2 className="text-base font-bold text-foreground">{selectedItem.title}</h2>
                    <p className="text-xs text-muted-foreground leading-normal mt-0.5">{selectedItem.description}</p>
                  </div>

                  {/* Context Cards depending on action type */}
                  {selectedItem.type === 'email' && (
                    <div className="border border-border/80 rounded-xl overflow-hidden bg-muted/5 flex flex-col text-xs">
                      <div className="p-3 bg-muted/10 border-b border-border flex flex-col gap-1.5">
                        <div className="flex items-center gap-1 text-[10px] text-muted-foreground">
                          <span className="font-bold w-12 shrink-0">TO:</span>
                          <span className="font-mono text-foreground font-semibold">{selectedItem.actionData.toName} &lt;{selectedItem.actionData.to}&gt;</span>
                        </div>
                        <div className="flex items-center gap-1 text-[10px] text-muted-foreground">
                          <span className="font-bold w-12 shrink-0">SUBJECT:</span>
                          <span className="text-foreground font-semibold">{selectedItem.actionData.subject}</span>
                        </div>
                      </div>
                      <div className="p-3 flex flex-col gap-1.5">
                        <label className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">Email Content Draft</label>
                        {selectedItem.status === 'pending' ? (
                          <textarea
                            value={editedBody}
                            onChange={(e) => setEditedBody(e.target.value)}
                            className="w-full bg-background border border-border rounded-lg p-3 text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500 text-foreground h-44 resize-none leading-relaxed"
                          />
                        ) : (
                          <p className="p-3 bg-background border border-border/40 rounded-lg text-xs leading-relaxed text-foreground whitespace-pre-wrap">
                            {selectedItem.actionData.body}
                          </p>
                        )}
                      </div>
                    </div>
                  )}

                  {selectedItem.type === 'crm' && (
                    <div className="border border-border rounded-xl p-4 bg-muted/5 flex flex-col gap-3 text-xs leading-normal">
                      <div className="flex items-center justify-between border-b border-border pb-2.5">
                        <span className="font-bold uppercase text-[9px] tracking-wider text-muted-foreground">Target CRM Pipeline Change</span>
                        <Badge variant="outline" className="uppercase text-[9px]">{(selectedItem.actionData?.targetStage || 'proposal').toUpperCase()} STAGE</Badge>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="flex-1 p-2 border border-border rounded bg-card text-center">
                          <span className="text-[9px] uppercase tracking-wider font-bold text-muted-foreground">Current Stage</span>
                          <div className="font-bold text-foreground capitalize mt-0.5">{targetDeal?.stage || 'lead'}</div>
                        </div>
                        <ArrowRight className="w-4 h-4 text-muted-foreground shrink-0" />
                        <div className="flex-1 p-2 border border-indigo-500/20 bg-indigo-500/[0.02] rounded text-center">
                          <span className="text-[9px] uppercase tracking-wider font-bold text-indigo-500">Proposed Stage</span>
                          <div className="font-bold text-indigo-500 capitalize mt-0.5">{selectedItem.actionData?.targetStage || 'proposal'}</div>
                        </div>
                      </div>
                      <p className="text-[10px] text-muted-foreground leading-normal mt-1 text-center">
                        This update will automatically move {targetDeal?.company || 'the deal'} on the CRM Board and recalculate weighted pipeline value.
                      </p>
                    </div>
                  )}

                  {selectedItem.type === 'meeting' && (
                    <div className="flex flex-col gap-4">
                      <div className="border border-border rounded-xl p-3 bg-muted/5 text-xs">
                        <span className="font-bold uppercase text-[9px] tracking-wider text-muted-foreground block mb-1.5">Meeting Executive Summary</span>
                        <p className="text-[11px] leading-relaxed text-foreground font-medium p-2.5 bg-card border border-border rounded-lg">
                          {selectedItem.actionData.summary}
                        </p>
                      </div>
                      
                      <div className="flex flex-col gap-2">
                        <span className="font-bold uppercase text-[9px] tracking-wider text-muted-foreground">Proposed tasks to generate ({selectedItem.actionData.extractedTasks.length})</span>
                        <div className="flex flex-col gap-1.5">
                          {selectedItem.actionData.extractedTasks.map((tText: string, idx: number) => (
                            <div key={idx} className="p-2 border border-border bg-card rounded-lg flex items-center gap-2 text-xs font-semibold">
                              <CheckSquare className="w-3.5 h-3.5 text-indigo-500 shrink-0" />
                              <span className="truncate">{tText}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                {/* Panel Footer Action bar */}
                <div className="p-4 border-t border-border bg-muted/10 shrink-0 flex gap-2 justify-end">
                  {selectedItem.status === 'pending' ? (
                    <>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => {
                          completeAiInboxItem(selectedItem.id);
                          setSelectedItemId(null);
                          toast.info('Action dismissed');
                        }}
                        className="text-muted-foreground hover:text-foreground cursor-pointer text-xs"
                      >
                        Dismiss Suggestion
                      </Button>
                      <Button
                        size="sm"
                        onClick={() => handleApproveAction(selectedItem)}
                        className="bg-indigo-600 hover:bg-indigo-600/90 text-white font-bold text-xs h-9 px-4 rounded-lg flex items-center gap-1.5 cursor-pointer"
                      >
                        <ShieldCheck className="w-4 h-4" /> Approve & Execute Action
                      </Button>
                    </>
                  ) : (
                    <div className="text-emerald-500 text-xs font-bold flex items-center gap-1">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500" /> Action Completed & Hydrated
                    </div>
                  )}
                </div>
              </motion.div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-center p-8 text-muted-foreground">
                <Sparkles className="w-12 h-12 opacity-15 mb-3 text-indigo-500" />
                <h4 className="text-xs font-bold text-foreground">Select Action Notification</h4>
                <p className="text-[10px] mt-1 max-w-[240px]">Select an AI notification action from the left list to review detailed parameters.</p>
              </div>
            )}
          </AnimatePresence>
        </div>

      </div>

    </div>
  );
}
